### ISSUE TITLE
[docs]: add code of conduct

### ISSUE THREAD

**Issue by akebu6** [girlscriptsiliguri/official-website#6]
I was taking a look at the repository and I was proposing that it have a code of conduct on how contributors are to conduct themselves. I would like to also work on it and add it to Hackertoberfest

**Comment by girlscriptsiliguri** [comment]
sure! go ahead.. have assigned you for the same
there are some code of conduct in general mentioned in contributing.md part but we need some help on the readme

**Comment by akebu6** [comment]
okay, what kind of help do you need with the readme?

And the code of conduct also needs to be linked in the CONTRIBUTING file because when clicked it brings a 404 page

**Comment by girlscriptsiliguri** [comment]
well it needs a better representation-all the sentences are clumped together there.
Also, the readme needs to be a summary of the content in all the .md files in this repo-which is there we think but you can add concise information surely
If you think that badges could be added to make it interesting, you could try it

**Comment by akebu6** [comment]
Can I open an issue for that or will you open it so that I can work on it?
